### ISSUE TITLE
IMAGEBUILDER Issue #1

### ISSUE THREAD

**Issue by Mutsuyoshi** [WobbyChip/Delphi#2]
No BSoD if chosen. Instead of image leads to DHCP Operating System Not Found Error. (No version could be provided: Only one avaliable) Device: VMware 16 Windows 7

**Comment by Mutsuyoshi** [comment]
I may have done something wrong or my browser has broken the app

**Comment by Mutsuyoshi** [comment]
UPDATE: Doesn't Reboot and leads to DHCP even with "Reboot" or "Nothing"

**Comment by WobbyChip** [comment]
I tried it on my virtual machine and it worked. I don't know what could be a possible issue why BSOD and Reboot don't work. But the reason for DHCP could be that your virtual machine is UEFI and this one doesn't work with UEFI.

**Comment by Mutsuyoshi** [comment]
Alright then i gonna find non-UEFI iso file, thanks for help!

**Comment by Mutsuyoshi** [comment]
I have checked firmware and it's not UEFI.

**Comment by Mutsuyoshi** [comment]
"test.exe has encountered a problem and needs to close. We are sorry for inconvenience." error message appears when Run as admin

**Comment by Mutsuyoshi** [comment]
![image](https://user-images.githubusercontent.com/74418423/157733486-ff7d5be2-0bee-4924-b7a9-db1c8eac4c7d.png)

**Comment by Mutsuyoshi** [comment]
Tried on WInXP with BIOS config. Didn't work as well.

**Comment by WobbyChip** [comment]
At this point, I really don't know what could be a possible issue.

**Comment by Mutsuyoshi** [comment]
Then it's VMware. Anyway thanks for help.

**Comment by Mutsuyoshi** [comment]
Yes, its VMware. I have checked the Firmware on vmx file and it was "efi" which stands for UEFI.

**Comment by teakatt** [comment]
UPDATED: UEFI BOOT SUPPORT is now disabled in BIOS. APCI error caused other problems (WinXP), on win7 was caused by VMRAM Failure
