### ISSUE TITLE
Hello WobbyChip.

### ISSUE THREAD

**Issue by Gocullinator** [WobbyChip/Delphi#4]
this is a comment for your program "MBR Note Builder" I would love to know the source code of the MBR, I don't want the code of the program that makes the mbr I just want the code of the mbr, so I would like you to send it to me, thanks for reading my comment.  

If you don't understand my English I'm very sorry, I'm from Argentina

have a nice day.

**Comment by WobbyChip** [comment]
https://github.com/WobbyChip/Delphi/blob/master/MBR%20UEFI%20-%20Note%20Builder/-(RES)-/CustomMBR.asm
