### ISSUE TITLE
How to compile? https://github.com/WobbyChip/Delphi/blob/master/MBR%20UEFI%20-%20Note%20Builder/-(RES)-/CustomMBR.asm#L3-L4

### ISSUE THREAD

**Issue by Gocullinator** [WobbyChip/Delphi#5]
Hello, thanks for answering me and sending me the source code, but what compiler do you use?  I have used several compilers and none works for me (I never used assembly)

**Comment by WobbyChip** [comment]
NASM Assembly

https://www.nasm.us/

Everything else, about how to compile you can find on google.
